[project]
name = "alzheption"
version = "0.0.1"
description = "The alzheimer classification app built in the Mathematics Thesis."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"